---
title: "Dashboard: Group 2 & 4"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    self_contained: FALSE
---

```{r setup, include=FALSE}
rm(list=ls(all=TRUE))

# Projectsettings
INSTALL_PACKAGES<-FALSE
if(INSTALL_PACKAGES)
{
install.packages(c("Boruta", "caTools", "corrplot", "dplyr", "e1071", "flexdashboard", "GeNetIt", "ggplot2", "gmodels", "ISLR", "lubridate", "mice", "missForest", "padr", "randomForest", "ranger", "RColorBrewer", "rpart.plot", "tidyr", "tidyverse"))
} else {
  print("#### NOTE: Package Installing is disabled. ####")
}

# Load in packages
library(foreign)
library(dplyr)
library(tidyr)
library(tidyverse)
library(padr)
library(lubridate)
library(class)
library(ggplot2)
library(caTools)
library(rpart)
library(e1071)
library(MASS)
library(gmodels)
library(ISLR)
library(rpart.plot)
library(randomForest)
library(nnet)
library(ranger)
library(Boruta)
library(mice)
library(missForest)
library(flexdashboard)
library(foreign)
library(GeNetIt)
library(ggplot2)
library(corrplot)
library(RColorBrewer)
library(reshape)

# Set this to climatedata file name
climatedatafile<-"climatedata.csv"
climatedataperdayfile<-"climatedataperday.csv"

# Irrigation system files
irrigation_system_1<-"irrigationsystem1.csv"
irrigation_system_2<-"irrigationsystem2.csv"

# Set this to harvestdata file name
harvestdatafile<-"harvestdata.csv"

# Customfunctions

# Removes all NA's from a column then returns the mean
MeanNoNA<-function(x){
	x<-na.omit(x)
	(mean(x))
}

MedianNoNA<-function(x){
	x<-na.omit(x)
	(median(x))
}

trainBorutaModel<-function(traindata){
  boruta.train <- Boruta(freshweight~., data = na.omit(traindata), doTrace=0)
  return(boruta.train)
}

# Boruta var selection
plotVarSelection<-function(traindata){
  traindata$averageWeight<-NULL
  plot(traindata, xlab = "", xaxt = "n")
  lz<-lapply(1:ncol(traindata$ImpHistory),function(i)
    traindata$ImpHistory[is.finite(traindata$ImpHistory[,i]),i])
  names(lz) <- colnames(traindata$ImpHistory)
  Labels <- sort(sapply(lz,median))
  axis(side = 1,las=2,labels = names(Labels),
       at = 1:ncol(traindata$ImpHistory), cex.axis = 0.7)
  
  TentativeRoughFix(traindata)
  #return(final.boruta$finalDecision)
}

completeHarvestData<-function(data){
  # Set up the traindata
  traindata<-data
  
  # Introduce Missing Values Completely At Random. 0.1 staat voor afwijking
  traindata.missing <- prodNA(traindata, noNA = 0.1)
  
  # Trainen kan niet met datums, weghalen
  traindata.missing$date<-NULL
  
  # Overzicht van de missende data
  # md.pattern(traindata.missing)
  
  # De missende data seeden
  # m is het aantal booststraps, meer is langer
  # maxit aantal iteraties, meer islanger
  # method pmm = predictive mean matching, kan ook meer: https://www.rdocumentation.org/packages/mice/versions/2.25/topics/mice, scroll naar "pmm section"
  imputed_Data <- mice(traindata.missing, m=5, maxit = 10, method = 'pmm', seed = 500)
  
  # 2 staat hier voor de boostrap nr, kan 1-10 zijn
  completeData<-complete(imputed_Data,2)
  
  completeData$date<-as.Date(data$date)
  
  return(completeData)
}

ClimateData<-read.csv(climatedatafile, header = TRUE, dec = ",", fill=TRUE, sep=";", stringsAsFactors = FALSE, fileEncoding="UTF-8-BOM")
print("ClimateData loaded in.")

ClimateDataPerDay<-read.csv(climatedataperdayfile, header = TRUE, dec = ",", fill=TRUE, sep=";", stringsAsFactors = FALSE, fileEncoding="UTF-8-BOM")
print("ClimateDataPerDay loaded in.")

HarvestData<-read.csv(harvestdatafile, header = TRUE, dec = ",", fill = FALSE, sep=";", stringsAsFactors = FALSE, fileEncoding="UTF-8-BOM")
print("HarvestData loaded in.")

IrrigationData1<-read.csv(irrigation_system_1, header = TRUE, dec = ",", fill=TRUE, sep=";", stringsAsFactors = FALSE, fileEncoding="UTF-8-BOM")
print("IrrigationData1 loaded in.")

IrrigationData2<-read.csv(irrigation_system_2, header = TRUE, dec = ",", fill=TRUE, sep=";", stringsAsFactors = FALSE, fileEncoding="UTF-8-BOM")
print("IrrigationData2 loaded in.")

# This file serves to clean the data.
options(digits=9)

# Assign datatypes to HarvestData
HarvestData$plant<-as.numeric(HarvestData$Plant.number)
HarvestData$date<-as.Date(HarvestData$date,format='%d/%m/%Y')
HarvestData$truss<-as.numeric(HarvestData$Truss.number)
HarvestData$brix<-as.numeric(HarvestData$Brix..Number.)
HarvestData$diameter<-as.numeric(HarvestData$Diameter.of.fruits..mm.)
HarvestData$fruits<-as.numeric(HarvestData$Number.of.fruits..Number.)
HarvestData$weightperfruit<-as.numeric(HarvestData$Weight.per.fruit..gr.)
HarvestData$freshweight<-as.numeric(HarvestData$Fresh.weight..gr.)
HarvestData$row_number<-NULL
HarvestData$Plant.number<-NULL
HarvestData$Truss.number<-NULL
HarvestData$Brix..Number.<-NULL
HarvestData$Diameter.of.fruits..mm.<-NULL
HarvestData$Number.of.fruits..Number.<-NULL
HarvestData$Weight.per.fruit..gr.<-NULL
HarvestData$Fresh.weight..gr.<-NULL

# Assign datatypes to ClimateData
ClimateData$date<-as.Date(ClimateData$date,format='%d-%m-%Y')
print("ClimateData cleaned up.")

# Assign datatypes to ClimateDataPerDay
ClimateDataPerDay$date<-as.Date(as.character(ClimateDataPerDay$date),format='%d-%m-%Y')
print("ClimateData cleaned up.")

# Assign datatypes to IrrigationData1
IrrigationData1$date<-as.Date(as.character(IrrigationData1$date),format='%d-%m-%Y')
print("IrrigationData1 cleaned up.")

# Assign datatypes to IrrigationData2
IrrigationData2$date<-as.Date(as.character(IrrigationData2$date),format='%d-%m-%Y')
print("IrrigationData2 cleaned up.")

# Merging scipt file
# This file is made to merge klimaatdata and growth harvest data (Reformatted)

system1<-merge(ClimateDataPerDay, IrrigationData1, by.x = "date", by.y = "date")
system2<-merge(ClimateDataPerDay, IrrigationData2, by.x = "date", by.y = "date")

HarvestDataToMerge<-completeHarvestData(HarvestData)

system1<-merge(system1, HarvestDataToMerge, by.x="date", by.y="date")
system2<-merge(system2, HarvestDataToMerge, by.x="date", by.y="date")

CherryTomaat<-system2[system2$plant>=400&system2$plant<=411,]
BigTomaat<-system1[system1$plant>=300&system1$plant<=311,]
PrunaxxTomaat<-system1[system1$plant>=500&system1$plant<=511,]
SmallTomaat<-system2[system2$plant>=600&system2$plant<=611,]

BigTomaat$averageWeight<-ifelse(BigTomaat$freshweight<mean(BigTomaat$freshweight),0,1)
BigTomaat$averageWeight<-as.factor(BigTomaat$averageWeight)
levels(BigTomaat$averageWeight)<-c("Low yield", "high yield")

PrunaxxTomaat$averageWeight<-ifelse(PrunaxxTomaat$freshweight<mean(PrunaxxTomaat$freshweight),0,1)
PrunaxxTomaat$averageWeight<-as.factor(PrunaxxTomaat$averageWeight)
levels(PrunaxxTomaat$averageWeight)<-c("Low yield", "high yield")

SmallTomaat$averageWeight<-ifelse(SmallTomaat$freshweight<mean(SmallTomaat$freshweight),0,1)
SmallTomaat$averageWeight<-as.factor(SmallTomaat$averageWeight)
levels(SmallTomaat$averageWeight)<-c("Low yield", "high yield")

CherryTomaat$averageWeight<-ifelse(CherryTomaat$freshweight<mean(CherryTomaat$freshweight),0,1)
CherryTomaat$averageWeight<-as.factor(CherryTomaat$averageWeight)
levels(CherryTomaat$averageWeight)<-c("Low yield", "high yield")

# normalize data

SmallTomaat$room.temperature.inside<-(SmallTomaat$room.temperature.inside-min(SmallTomaat$room.temperature.inside))/(max(SmallTomaat$room.temperature.inside)-min(SmallTomaat$room.temperature.inside))
SmallTomaat$air.humidity<-(SmallTomaat$air.humidity-min(SmallTomaat$air.humidity))/(max(SmallTomaat$air.humidity)-min(SmallTomaat$air.humidity))

SmallTomaat$CO2.amount<-(SmallTomaat$CO2.amount-min(SmallTomaat$CO2.amount))/(max(SmallTomaat$CO2.amount)-min(SmallTomaat$CO2.amount))

SmallTomaat$radiation.outside<-(SmallTomaat$radiation.outside-min(SmallTomaat$radiation.outside))/(max(SmallTomaat$radiation.outside)-min(SmallTomaat$radiation.outside))

SmallTomaat$plant.temperature.big<-(SmallTomaat$plant.temperature.big-min(SmallTomaat$plant.temperature.big))/(max(SmallTomaat$plant.temperature.big)-min(SmallTomaat$plant.temperature.big))

SmallTomaat$plant.temperature.small<-(SmallTomaat$plant.temperature.small-min(SmallTomaat$plant.temperature.small))/(max(SmallTomaat$plant.temperature.small)-min(SmallTomaat$plant.temperature.small))

SmallTomaat$Average.EC<-(SmallTomaat$Average.EC-min(SmallTomaat$Average.EC))/(max(SmallTomaat$Average.EC)-min(SmallTomaat$Average.EC))

SmallTomaat$Average.Flow<-(SmallTomaat$Average.Flow-min(SmallTomaat$Average.Flow))/(max(SmallTomaat$Average.Flow)-min(SmallTomaat$Average.Flow))

SmallTomaat$Sum.LitersPerM2<-(SmallTomaat$Sum.LitersPerM2-min(SmallTomaat$Sum.LitersPerM2))/(max(SmallTomaat$Sum.LitersPerM2)-min(SmallTomaat$Sum.LitersPerM2))

SmallTomaat$Sum.Deviation<-(SmallTomaat$Sum.Deviation-min(SmallTomaat$Sum.Deviation))/(max(SmallTomaat$Sum.Deviation)-min(SmallTomaat$Sum.Deviation))

SmallTomaat$Sum.TotalLiters<-(SmallTomaat$Sum.TotalLiters-min(SmallTomaat$Sum.TotalLiters))/(max(SmallTomaat$Sum.TotalLiters)-min(SmallTomaat$Sum.TotalLiters))

SmallTomaat$Sum.Usage<-(SmallTomaat$Sum.Usage-min(SmallTomaat$Sum.Usage))/(max(SmallTomaat$Sum.Usage)-min(SmallTomaat$Sum.Usage))

SmallTomaat$drain.percentage<-(SmallTomaat$drain.percentage-min(SmallTomaat$drain.percentage))/(max(SmallTomaat$drain.percentage)-min(SmallTomaat$drain.percentage))

SmallTomaat$EC<-(SmallTomaat$EC-min(SmallTomaat$EC))/(max(SmallTomaat$EC)-min(SmallTomaat$EC))
SmallTomaat$drain.water.amount<-(SmallTomaat$drain.water.amount-min(SmallTomaat$drain.water.amount))/(max(SmallTomaat$drain.water.amount)-min(SmallTomaat$drain.water.amount))

SmallTomaat$absorb.water.amount<-(SmallTomaat$absorb.water.amount-min(SmallTomaat$absorb.water.amount))/(max(SmallTomaat$absorb.water.amount)-min(SmallTomaat$absorb.water.amount))

SmallTomaat$truss<-(SmallTomaat$truss-min(SmallTomaat$truss))/(max(SmallTomaat$truss)-min(SmallTomaat$truss))

SmallTomaat$brix<-(SmallTomaat$brix-min(SmallTomaat$brix))/(max(SmallTomaat$brix)-min(SmallTomaat$brix))

SmallTomaat$fruits<-(SmallTomaat$fruits-min(SmallTomaat$fruits))/(max(SmallTomaat$fruits)-min(SmallTomaat$fruits))

SmallTomaat$weightperfruit<-(SmallTomaat$weightperfruit-min(SmallTomaat$weightperfruit))/(max(SmallTomaat$weightperfruit)-min(SmallTomaat$weightperfruit))
SmallTomaat$drain.water.amount<-(SmallTomaat$drain.water.amount-min(SmallTomaat$drain.water.amount))/(max(SmallTomaat$drain.water.amount)-min(SmallTomaat$drain.water.amount))

SmallTomaat$pH<-(SmallTomaat$pH-min(SmallTomaat$pH))/(max(SmallTomaat$pH)-min(SmallTomaat$pH))

SmallTomaat$diameter<-(SmallTomaat$diameter-min(SmallTomaat$diameter))/(max(SmallTomaat$diameter)-min(SmallTomaat$diameter))

SmallTomaat$freshweight<-(SmallTomaat$freshweight-min(SmallTomaat$freshweight))/(max(SmallTomaat$freshweight)-min(SmallTomaat$freshweight))


# set data in new variable drain vs freshweight
DrainTableSmall=data.frame(SmallTomaat$date,SmallTomaat$drain.water.amount,SmallTomaat$freshweight)

DrainTableSmall <- melt(DrainTableSmall, id.vars =c("SmallTomaat.date"))

# set data in new variable drain vs freshweight
DiameterTableSmall=data.frame(SmallTomaat$date,SmallTomaat$diameter,SmallTomaat$freshweight)

DiameterTableSmall <- melt(DiameterTableSmall, id.vars =c("SmallTomaat.date"))


# set data in new variable ph vs diameter
phTableSmall=data.frame(SmallTomaat$date,SmallTomaat$diameter,SmallTomaat$pH)

phTableSmall <- melt(phTableSmall, id.vars =c("SmallTomaat.date"))


# set data in new variable ph vs diameter
RoomTepTableSmall=data.frame(SmallTomaat$date,SmallTomaat$room.temperature.inside,SmallTomaat$freshweight)

RoomTepTableSmall <- melt(RoomTepTableSmall, id.vars =c("SmallTomaat.date"))

# set data in new variable ph vs diameter
PhVSTempinsideTableSmall=data.frame(SmallTomaat$date,SmallTomaat$room.temperature.inside,SmallTomaat$pH)

PhVSTempinsideTableSmall <- melt(PhVSTempinsideTableSmall, id.vars =c("SmallTomaat.date"))

# set data in new variable ph vs diameter
litersTableSmall=data.frame(SmallTomaat$date,SmallTomaat$Sum.LitersPerM2,SmallTomaat$freshweight)

litersTableSmall <- melt(litersTableSmall, id.vars =c("SmallTomaat.date"))

EcTableSmall=data.frame(SmallTomaat$date,SmallTomaat$EC,SmallTomaat$pH)

EcTableSmall <- melt(EcTableSmall, id.vars =c("SmallTomaat.date"))

AbsorbTableSmall=data.frame(SmallTomaat$date,SmallTomaat$absorb.water.amount,SmallTomaat$brix)

AbsorbTableSmall <- melt(AbsorbTableSmall, id.vars =c("SmallTomaat.date"))

FlowTableSmall=data.frame(SmallTomaat$date,SmallTomaat$Average.Flow,SmallTomaat$freshweight)

FlowTableSmall <- melt(FlowTableSmall, id.vars =c("SmallTomaat.date"))

# normalize data bigTomaat

BigTomaat$room.temperature.inside<-(BigTomaat$room.temperature.inside-min(BigTomaat$room.temperature.inside))/(max(BigTomaat$room.temperature.inside)-min(BigTomaat$room.temperature.inside))
BigTomaat$air.humidity<-(BigTomaat$air.humidity-min(BigTomaat$air.humidity))/(max(BigTomaat$air.humidity)-min(BigTomaat$air.humidity))

BigTomaat$CO2.amount<-(BigTomaat$CO2.amount-min(BigTomaat$CO2.amount))/(max(BigTomaat$CO2.amount)-min(BigTomaat$CO2.amount))

BigTomaat$plant.temperature.big<-(BigTomaat$plant.temperature.big-min(BigTomaat$plant.temperature.big))/(max(BigTomaat$plant.temperature.big)-min(BigTomaat$plant.temperature.big))


BigTomaat$Average.EC<-(BigTomaat$Average.EC-min(BigTomaat$Average.EC))/(max(BigTomaat$Average.EC)-min(BigTomaat$Average.EC))

BigTomaat$Average.Flow<-(BigTomaat$Average.Flow-min(BigTomaat$Average.Flow))/(max(BigTomaat$Average.Flow)-min(BigTomaat$Average.Flow))

BigTomaat$Sum.LitersPerM2<-(BigTomaat$Sum.LitersPerM2-min(BigTomaat$Sum.LitersPerM2))/(max(BigTomaat$Sum.LitersPerM2)-min(BigTomaat$Sum.LitersPerM2))

BigTomaat$Sum.Deviation<-(BigTomaat$Sum.Deviation-min(BigTomaat$Sum.Deviation))/(max(BigTomaat$Sum.Deviation)-min(BigTomaat$Sum.Deviation))

BigTomaat$Sum.TotalLiters<-(BigTomaat$Sum.TotalLiters-min(BigTomaat$Sum.TotalLiters))/(max(BigTomaat$Sum.TotalLiters)-min(BigTomaat$Sum.TotalLiters))

BigTomaat$Sum.Usage<-(BigTomaat$Sum.Usage-min(BigTomaat$Sum.Usage))/(max(BigTomaat$Sum.Usage)-min(BigTomaat$Sum.Usage))

BigTomaat$drain.percentage<-(BigTomaat$drain.percentage-min(BigTomaat$drain.percentage))/(max(BigTomaat$drain.percentage)-min(BigTomaat$drain.percentage))

BigTomaat$EC<-(BigTomaat$EC-min(BigTomaat$EC))/(max(BigTomaat$EC)-min(BigTomaat$EC))
BigTomaat$drain.water.amount<-(BigTomaat$drain.water.amount-min(BigTomaat$drain.water.amount))/(max(BigTomaat$drain.water.amount)-min(BigTomaat$drain.water.amount))

BigTomaat$absorb.water.amount<-(BigTomaat$absorb.water.amount-min(BigTomaat$absorb.water.amount))/(max(BigTomaat$absorb.water.amount)-min(BigTomaat$absorb.water.amount))

BigTomaat$truss<-(BigTomaat$truss-min(BigTomaat$truss))/(max(BigTomaat$truss)-min(BigTomaat$truss))

BigTomaat$brix<-(BigTomaat$brix-min(BigTomaat$brix))/(max(BigTomaat$brix)-min(BigTomaat$brix))

BigTomaat$fruits<-(BigTomaat$fruits-min(BigTomaat$fruits))/(max(BigTomaat$fruits)-min(BigTomaat$fruits))

BigTomaat$weightperfruit<-(BigTomaat$weightperfruit-min(BigTomaat$weightperfruit))/(max(BigTomaat$weightperfruit)-min(BigTomaat$weightperfruit))
BigTomaat$drain.water.amount<-(BigTomaat$drain.water.amount-min(BigTomaat$drain.water.amount))/(max(BigTomaat$drain.water.amount)-min(BigTomaat$drain.water.amount))

BigTomaat$pH<-(BigTomaat$pH-min(BigTomaat$pH))/(max(BigTomaat$pH)-min(BigTomaat$pH))

BigTomaat$diameter<-(BigTomaat$diameter-min(BigTomaat$diameter))/(max(BigTomaat$diameter)-min(BigTomaat$diameter))

BigTomaat$freshweight<-(BigTomaat$freshweight-min(BigTomaat$freshweight))/(max(BigTomaat$freshweight)-min(BigTomaat$freshweight))


# set data in new variable drain vs freshweight
DrainTableBig=data.frame(BigTomaat$date,BigTomaat$drain.water.amount,BigTomaat$freshweight)

DrainTableBig <- melt(DrainTableBig, id.vars =c("BigTomaat.date"))

# set data in new variable drain vs freshweight
DiameterTableBig=data.frame(BigTomaat$date,BigTomaat$diameter,BigTomaat$freshweight)

DiameterTableBig <- melt(DiameterTableBig, id.vars =c("BigTomaat.date"))


# set data in new variable ph vs diameter
phTableBig=data.frame(BigTomaat$date,BigTomaat$diameter,BigTomaat$pH)

phTableBig <- melt(phTableBig, id.vars =c("BigTomaat.date"))


# set data in new variable ph vs diameter
RoomTepTableBig=data.frame(BigTomaat$date,BigTomaat$room.temperature.inside,BigTomaat$freshweight)

RoomTepTableBig <- melt(RoomTepTableBig, id.vars =c("BigTomaat.date"))

# set data in new variable ph vs diameter
PhVSTempinsideTableBig=data.frame(BigTomaat$date,BigTomaat$room.temperature.inside,BigTomaat$pH)

PhVSTempinsideTableBig <- melt(PhVSTempinsideTableBig, id.vars =c("BigTomaat.date"))

# set data in new variable ph vs diameter
litersTableBig=data.frame(BigTomaat$date,BigTomaat$Sum.LitersPerM2,BigTomaat$freshweight)

litersTableBig <- melt(litersTableBig, id.vars =c("BigTomaat.date"))

EcTableBig=data.frame(BigTomaat$date,BigTomaat$EC,BigTomaat$pH)

EcTableBig <- melt(EcTableBig, id.vars =c("BigTomaat.date"))

AbsorbTableBig=data.frame(BigTomaat$date,BigTomaat$absorb.water.amount,BigTomaat$brix)

AbsorbTableBig <- melt(AbsorbTableBig, id.vars =c("BigTomaat.date"))

FlowTableBig=data.frame(BigTomaat$date,BigTomaat$Average.Flow,BigTomaat$freshweight)

FlowTableBig <- melt(FlowTableBig, id.vars =c("BigTomaat.date"))
#normalizebigtomaat stops here


borutaTrainData<-CherryTomaat
borutaTrainData$averageWeight<-NULL
borutaCherryTomaat<-trainBorutaModel(borutaTrainData)

borutaTrainData<-BigTomaat
borutaTrainData$averageWeight<-NULL
borutaBigTomaat<-trainBorutaModel(borutaTrainData)

borutaTrainData<-PrunaxxTomaat
borutaTrainData$averageWeight<-NULL
borutaPrunaxxTomaat<-trainBorutaModel(borutaTrainData)

borutaTrainData<-SmallTomaat
borutaTrainData$averageWeight<-NULL
borutaSmallTomaat<-trainBorutaModel(borutaTrainData)

```

Boruta Variable Selection
=====================================
knn {.tabset}
---------------------------------------------------------------------

### Cherry

```{r}


plotVarSelection(borutaCherryTomaat)
```

### Big

```{r}
plotVarSelection(borutaBigTomaat)
```

### Prunaxx

```{r}
plotVarSelection(borutaPrunaxxTomaat)
```

### Small

```{r}
plotVarSelection(borutaSmallTomaat)
```

Corrplot
=====================================
Correlation {.tabset}
---------------------------------------------------------------------
   
### Cherry
    
```{r}
temp<-CherryTomaat
temp$date<-NULL
temp$soort<-NULL
temp$averageWeight<-NULL
temp$radiation.outside<-NULL
temp$plant<-NULL
temp$truss<-NULL
temp<-na.omit(temp)
corrplot.mixed(cor(temp), tl.pos = "lt", lower = "number", upper = "shade", number.cex=0.25, order = "AOE")
temp<-NULL
```

### Big
    
```{r}
temp<-BigTomaat
temp$date<-NULL
temp$soort<-NULL
temp$averageWeight<-NULL
temp$radiation.outside<-NULL
temp$plant<-NULL
temp$truss<-NULL
temp<-na.omit(temp)
test<-cor(temp)
corrplot.mixed(test, tl.pos = "lt", lower = "number", upper = "shade", number.cex=0.25, order = "AOE")
temp<-NULL
```

### Prunaxx
    
```{r}
temp<-PrunaxxTomaat
temp$date<-NULL
temp$soort<-NULL
temp$averageWeight<-NULL
temp$radiation.outside<-NULL
temp$plant<-NULL
temp$truss<-NULL
temp<-na.omit(temp)
corrplot.mixed(cor(temp), tl.pos = "lt", lower = "number", upper = "shade", number.cex=0.25, order = "AOE")
temp<-NULL
```

### Small
    
```{r}
temp<-SmallTomaat
temp$date<-NULL
temp$soort<-NULL
temp$averageWeight<-NULL
temp$radiation.outside<-NULL
temp$plant<-NULL
temp$truss<-NULL
temp<-na.omit(temp)
corrplot.mixed(cor(temp), tl.pos = "lt", lower = "number", upper = "shade", number.cex=0.25, order = "AOE")
temp<-NULL
```

<!-- K Nearest -->
<!-- ===================================== -->

<!-- knn {.tabset} -->
<!-- ----------------------------------------------------------------------- -->
<!-- ### Cherry -->

<!-- ```{r} -->
<!-- # test data: -->
<!-- testData<-CherryTomaat[1:120, ] -->
<!-- testData$date<-NULL -->
<!-- testData$averageWeight<-NULL -->


<!-- # train data: -->
<!-- trainData<-SmallTomaat[120:165,] -->
<!-- trainData$date<-NULL -->
<!-- trainData$averageWeight<-NULL -->

<!-- train_labels<-SmallTomaat[120:165,15] -->
<!-- train_test_category <- SmallTomaat[-120,15] -->

<!-- result<-knn(test = na.omit(testData), train = na.omit(trainData), k = 8, cl = na.omit(train_labels)) -->

<!-- ``` -->

<!-- ### Big -->

<!-- ```{r} -->
<!-- # test data: -->
<!-- testData<-BigTomaat[1:60,] -->
<!-- testData$date<-NULL -->
<!-- testData$averageWeight<-NULL -->
<!-- testData$radiation.outside<-NULL -->


<!-- # train data: -->
<!-- trainData<-BigTomaat[60:80,] -->
<!-- trainData$date<-NULL -->
<!-- trainData$averageWeight<-NULL -->
<!-- trainData$radiation.outside<-NULL -->

<!-- train_labels<-BigTomaat[60:80,15] -->
<!-- train_test_category <- BigTomaat[-80,15] -->

<!-- result<-knn(test = na.omit(testData), train = na.omit(trainData), k = 8, cl = na.omit(train_labels)) -->

<!-- #table(train_test_category,temp) -->
<!-- ``` -->

<!-- ### Prunaxx -->

<!-- ```{r} -->
<!-- # test data: -->
<!-- testData<-PrunaxxTomaat[1:60, ] -->
<!-- testData$date<-NULL -->
<!-- testData$averageWeight<-NULL -->
<!-- testData$radiation.outside<-NULL -->


<!-- # train data: -->
<!-- trainData<-PrunaxxTomaat[60:83,] -->
<!-- trainData$date<-NULL -->
<!-- trainData$averageWeight<-NULL -->
<!-- trainData$radiation.outside<-NULL -->

<!-- train_labels<-PrunaxxTomaat[60:83,15] -->
<!-- train_test_category <- PrunaxxTomaat[-60,15] -->

<!-- result<-knn(test = na.omit(testData), train = na.omit(trainData), k = 8, cl = na.omit(train_labels)) -->

<!-- #table(train_test_category,temp) -->
<!-- ``` -->

<!-- ### Small -->

<!-- ```{r} -->
<!-- # test data: -->
<!-- testData<-SmallTomaat[1:110, ] -->
<!-- testData$date<-NULL -->
<!-- testData$averageWeight<-NULL -->
<!-- testData$radiation.outside<-NULL -->

<!-- # train data: -->
<!-- trainData<-SmallTomaat[110:137,] -->
<!-- trainData$date<-NULL -->
<!-- trainData$averageWeight<-NULL -->
<!-- trainData$radiation.outside<-NULL -->

<!-- train_labels<-SmallTomaat[110:137,15] -->
<!-- train_test_category <- SmallTomaat[-110,15] -->

<!-- result<-knn(test = na.omit(testData), train = na.omit(trainData), k = 8, cl = na.omit(train_labels)) -->

<!-- ``` -->
Random Forest
=====================================
Forest {.tabset}
-----------------------------------------------------------------------

### Cherry

```{r}

CherryTomaat$date<-NULL
BigTomaat$date<-NULL
PrunaxxTomaat$date<-NULL
SmallTomaat$date<-NULL
rfModel<-randomForest(
		averageWeight~.-averageWeight-freshweight-weightperfruit-brix-diameter-fruits-plant-truss,
		data=CherryTomaat,
		ntree=100,importance=TRUE)
rfProbs<-predict(rfModel,type="prob")[,"Low yield"]
AUCrf<-colAUC(rfProbs,CherryTomaat$averageWeight,alg="ROC",plot=T)
AUCrf
varImpPlot(rfModel,sort=TRUE)

```

### Big

```{r}

rfModel<-randomForest(
		averageWeight~.-averageWeight-freshweight-weightperfruit-brix-diameter-fruits-plant-truss,
		data=BigTomaat,
		ntree=100,importance=TRUE)
rfProbs<-predict(rfModel,type="prob")[,"Low yield"]
AUCrf<-colAUC(rfProbs,BigTomaat$averageWeight,alg="ROC",plot=T)
AUCrf
varImpPlot(rfModel,sort=TRUE)

```

### Prunaxx

````{r}

rfModel<-randomForest(
		averageWeight~.-averageWeight-freshweight-weightperfruit-brix-diameter-fruits-plant-truss,
		data=PrunaxxTomaat,
		ntree=100,importance=TRUE)
rfProbs<-predict(rfModel,type="prob")[,"Low yield"]
AUCrf<-colAUC(rfProbs,PrunaxxTomaat$averageWeight,alg="ROC",plot=T)
AUCrf
varImpPlot(rfModel,sort=TRUE)

```

### Small

```{r}

rfModel<-randomForest(
		averageWeight~.-averageWeight-freshweight-weightperfruit-brix-diameter-fruits-plant-truss,
		data=SmallTomaat,
		ntree=100,importance=TRUE)
rfProbs<-predict(rfModel,type="prob")[,"Low yield"]
AUCrf<-colAUC(rfProbs,SmallTomaat$averageWeight,alg="ROC",plot=T)
AUCrf
varImpPlot(rfModel,sort=TRUE)

```


Nnet
=====================================
column {.tabset}
-----------------------------------------------------------------------
### Cherry
```{r}
CherryTomaat$date=NULL
CherryTomaat$averagefruitss=NULL
nnModel<-nnet(averageWeight~.,data=CherryTomaat,maxit=100,size=20)
nnProbs<-predict(nnModel)
AUCnn<-colAUC(nnProbs,CherryTomaat$averageWeight,alg="ROC",plot=T)
AUCnn
```

### Small
```{r}
SmallTomaat$date=NULL
SmallTomaat$averagefruitss=NULL
nnModel<-nnet(averageWeight~.,data=SmallTomaat,maxit=100,size=20)
nnProbs<-predict(nnModel)
AUCnn<-colAUC(nnProbs,SmallTomaat$averageWeight,alg="ROC",plot=T)
AUCnn
```

### Big
```{r}
BigTomaat$date=NULL
BigTomaat$averagefruitss=NULL
nnModel<-nnet(averageWeight~.,data=BigTomaat,maxit=100,size=20)
nnProbs<-predict(nnModel)
AUCnn<-colAUC(nnProbs,BigTomaat$averageWeight,alg="ROC",plot=T)
AUCnn
```


### Prunaxx
```{r}
PrunaxxTomaat$date=NULL
PrunaxxTomaat$averagefruitss=NULL
nnModel<-nnet(averageWeight~.,data=PrunaxxTomaat,maxit=100,size=20)
nnProbs<-predict(nnModel)
AUCnn<-colAUC(nnProbs,PrunaxxTomaat$averageWeight,alg="ROC",plot=T)
AUCnn
```


SVM
=====================================
svm {.tabset}
-----------------------------------------------------------------------

### Cherry

```{r}
m <- svm(averageWeight~. , data = CherryTomaat)

plot(m, CherryTomaat, freshweight~drain.water.amount)
```

### Big

```{r}
m <- svm(averageWeight~., data = BigTomaat)

plot(m, BigTomaat, freshweight~drain.water.amount)
```

### Prunaxx

```{r}
m <- svm(averageWeight~., data = PrunaxxTomaat)

plot(m, PrunaxxTomaat, freshweight~drain.water.amount)
```

### SmallTomato

```{r}
m <- svm(averageWeight~., data = SmallTomaat)

print(m)
plot(m, SmallTomaat, freshweight~drain.water.amount)
```

GGplots
=====================================
plots {.tabset}
-----------------------------------------------------------------------
### Smalltomato

```{r}
# GGplot pH and Brix
ggplot(phTableSmall, aes(x = SmallTomaat.date, y = value, colour = variable)) + 
    geom_smooth() + geom_point()

ggplot(DrainTableSmall, aes(x = SmallTomaat.date, y = value, colour = variable)) + 
    geom_smooth() + geom_point()

ggplot(DiameterTableSmall, aes(x = SmallTomaat.date, y = value, colour = variable)) + 
    geom_smooth() + geom_point()

ggplot(RoomTepTableSmall, aes(x = SmallTomaat.date, y = value, colour = variable)) + 
    geom_smooth() + geom_point()

ggplot(PhVSTempinsideTableSmall, aes(x = SmallTomaat.date, y = value, colour = variable)) + 
    geom_smooth() + geom_point()

ggplot(litersTableSmall, aes(x = SmallTomaat.date, y = value, colour = variable)) + 
    geom_smooth() + geom_point()

ggplot(EcTableSmall, aes(x = SmallTomaat.date, y = value, colour = variable)) + 
    geom_smooth() + geom_point()


ggplot(AbsorbTableSmall, aes(x = SmallTomaat.date, y = value, colour = variable)) + 
    geom_smooth() + geom_point()

ggplot(FlowTableSmall, aes(x = SmallTomaat.date, y = value, colour = variable)) + 
    geom_smooth() + geom_point()

```

### Bigtomato

```{r}
# GGplot pH and Brix
ggplot(phTableBig, aes(x = BigTomaat.date, y = value, colour = variable)) + 
    geom_smooth() + geom_point()

ggplot(DrainTableBig, aes(x = BigTomaat.date, y = value, colour = variable)) + 
    geom_smooth() + geom_point()

ggplot(DiameterTableBig, aes(x = BigTomaat.date, y = value, colour = variable)) + 
    geom_smooth() + geom_point()

ggplot(RoomTepTableBig, aes(x = BigTomaat.date, y = value, colour = variable)) + 
    geom_smooth() + geom_point()

ggplot(PhVSTempinsideTableBig, aes(x = BigTomaat.date, y = value, colour = variable)) + 
    geom_smooth() + geom_point()

ggplot(litersTableBig, aes(x = BigTomaat.date, y = value, colour = variable)) + 
    geom_smooth() + geom_point()

ggplot(EcTableBig, aes(x = BigTomaat.date, y = value, colour = variable)) + 
    geom_smooth() + geom_point()

ggplot(AbsorbTableBig, aes(x = BigTomaat.date, y = value, colour = variable)) + 
    geom_smooth() + geom_point()

ggplot(FlowTableBig, aes(x = BigTomaat.date, y = value, colour = variable)) + 
    geom_smooth() + geom_point()

```
